---
title: "`r params$report_title`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    code_folding: hide
params:
  report_title: "Binding of epitope peptides to MHC"
  report_author: "Tamas Szabo"
  mhc_table: "../tables/netMHC_results.csv"
---

## Setup

```{r results="hide", message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(plotly)
library(RColorBrewer)

filter <- dplyr::filter
select <- dplyr::select
arrange <- dplyr::arrange

color_names <- c("#E64B35B2", "#4DBBD5B2", "#00A087B2", "#3C5488B2", "#F39B7FB2", "#8491B4B2")
```

## MHC binding

```{r}
mhci_tab <- params$mhc_table %>%
  read.csv() %>%
  mutate(
    affinity = 1/log10(nM)
  ) %>%
  left_join(select(freq_tab, Allele, permille), by="Allele") %>%
  arrange(Allele, Peptide)

head(mhc_tab)
```

```{r fig.width=9.6, fig.height=13.4}
mhc_tab %>%
  mutate(
    Allele = factor(Allele, levels=rev(unique(mhc_tab$Allele)))
  ) %>%
  filter(!is.na(Peptide)) %>%
  ggplot(aes(x=Peptide, y=Allele, fill=affinity)) +
  geom_tile() +
  scale_fill_gradientn(colors=brewer.pal(5, "Blues")) +
  theme_bw() +
  theme(
    axis.text.x=element_text(angle=30, hjust=1),
    axis.text.y=element_text(size=8)
  ) +
  labs(
    x = "", y = "", title = "Predicted MHC binding affinity"
  )
```

```{r}
p <- mhc_tab %>%
  mutate(
    Allele = factor(Allele, levels=rev(unique(mhc_tab$Allele)))
  ) %>%
  ggplot(aes(x=Peptide, y=Allele, size=affinity, color=affinity)) +
  geom_point() +
  scale_colour_gradientn(colors=brewer.pal(5, "Reds")) +
  theme_bw() +
  theme(
    axis.text.x=element_text(angle=30, hjust=1),
    axis.text.y=element_text(size=8)
  ) +
  labs(
    x = "", y = "", color = "Affinity", size = "Affinity (1-log50k(nM))",
    title = "Predicted binding affinity to MHC alleles"
  )

ggplotly(p, width=800, height=1200)
```